flowchart TD
L[执行任务规则]-->A
A[编写代码规则] --> A1[当问题是功能性需求时]
L --> D[执行自动化指令报错时]
D --> D1[当修复错误好，把正确的调用方法写入到'自动化操作指令.md'内,要求尽量简洁比如powershell运行文件命令按照该格式 .\文件名]

L --> C[调用自动化指令时优先使用文档'自动化操作指令.md'内的命令]
A1 --> B[代码编写风格]
A1 --> A11[读取“项目记忆文档.md”,确认该功能需求是否有类似的功能]
A11 -- 有 --> A111[读取类似功能代码调用的逻辑]
A11 -- 无 --> A112[读取整个项目代码调用逻辑，查找需要创建该功能时需要用到的关联组件和函数]
A112 --> A1121[将关联组件或函数的调用逻辑整理写入到“项目记忆文档.md”内]
A1121-->A12[编写新功能代码]
A111 -->A1112[根据用现有功能的逻辑添加该功能新的对象来实现需求]
A1112-->A121
A12 --> A121[编译项目]
A121 --> A122[编译成功后运行程序]
A122 --> A123[读取日志确保功能实现]
B-->B1[必须实现功能的函数模块化，尽量和程序解耦]
B-->B2[调用的库必须基于项目引用的库版本]
B-->B3[思考新模块如何通过log日志确认功能可以实现]





